In [1]:
import pdal 
import numpy as np
import matplotlib.pyplot as plt
from scipy.spatial import KDTree
from scipy.linalg import svd 
from osgeo import ogr
import pyvista as pv
import os
import json
import time 

In [2]:
filename = "abseits1.las"

filename = os.path.join("/home/riannek/code/gleis/versuche/template_versuchsdaten", filename)

In [3]:
pipeline = pdal.Pipeline([pdal.Reader(filename)])
pipeline.execute()
points = pipeline.arrays[0]
points.dtype # Column names and types

dtype([('X', '<f8'), ('Y', '<f8'), ('Z', '<f8'), ('Intensity', '<u2'), ('ReturnNumber', 'u1'), ('NumberOfReturns', 'u1'), ('ScanDirectionFlag', 'u1'), ('EdgeOfFlightLine', 'u1'), ('Classification', 'u1'), ('Synthetic', 'u1'), ('KeyPoint', 'u1'), ('Withheld', 'u1'), ('Overlap', 'u1'), ('ScanAngleRank', '<f4'), ('UserData', 'u1'), ('PointSourceId', '<u2'), ('GpsTime', '<f8'), ('ScanChannel', 'u1'), ('Red', '<u2'), ('Green', '<u2'), ('Blue', '<u2')])

In [5]:
xyz = np.vstack((points['X'], points['Y'], points['Z'])).T
mean = np.mean(xyz, axis=0)
xyz -= mean  

In [11]:
n = xyz.shape[0]

In [9]:
np.cov(xyz.T)

array([[ 0.0527651 , -0.14828021,  0.00068543],
       [-0.14828021,  0.41852224, -0.00118485],
       [ 0.00068543, -0.00118485,  0.00109442]])

In [13]:
np.cov(xyz.T)

array([[ 0.0527651 , -0.14828021,  0.00068543],
       [-0.14828021,  0.41852224, -0.00118485],
       [ 0.00068543, -0.00118485,  0.00109442]])

In [ ]:
(xyz @ xyz.T) 

array([[ 2.46498488e-03,  2.08655160e-03, -5.27757883e-03, ...,
        -3.60165045e-04,  2.95888293e-03, -3.89798364e-03],
       [ 2.08655160e-03,  1.81420527e-03, -4.48905560e-03, ...,
        -2.95120069e-04,  2.56827574e-03, -3.31989519e-03],
       [-5.27757883e-03, -4.48905560e-03,  1.13094227e-02, ...,
         7.66836450e-04, -6.36368079e-03,  8.35510482e-03],
       ...,
       [-3.60165045e-04, -2.95120069e-04,  7.66836450e-04, ...,
         5.46850278e-05, -4.19310473e-04,  5.65562088e-04],
       [ 2.95888293e-03,  2.56827574e-03, -6.36368079e-03, ...,
        -4.19310473e-04,  3.63625924e-03, -4.70582472e-03],
       [-3.89798364e-03, -3.31989519e-03,  8.35510482e-03, ...,
         5.65562088e-04, -4.70582472e-03,  6.17296089e-03]])

In [14]:
xyz.T @ xyz * (1/(n-1))

array([[ 0.0527651 , -0.14828021,  0.00068543],
       [-0.14828021,  0.41852224, -0.00118485],
       [ 0.00068543, -0.00118485,  0.00109442]])