# Versuche mit Transformationen

In [1]:
import numpy as np

In [2]:
R = np.array([[ 0.9932866 , -0.11430465, -0.01778151],
       [ 0.11422393,  0.99343984, -0.00549424],
       [ 0.01829287,  0.00342628,  0.9998268 ]])

R  

array([[ 0.9932866 , -0.11430465, -0.01778151],
       [ 0.11422393,  0.99343984, -0.00549424],
       [ 0.01829287,  0.00342628,  0.9998268 ]])

In [4]:
R.T @ R # Sollte Einheitsmatrix sein wenn reine Rotation

array([[ 1.00000001e+00,  2.07530480e-09, -7.62101320e-09],
       [ 2.07530480e-09,  1.00000001e+00, -1.06119610e-09],
       [-7.62101320e-09, -1.06119610e-09,  9.99999999e-01]])

In [5]:
np.linalg.det(R) # Determinante sollte 1 sein wenn reine Rotation

np.float64(1.0000000059459129)

In [7]:
point = np.array([1, 0, 0])
point.shape  

(3,)

In [8]:
point @ R.T

array([0.9932866 , 0.11422393, 0.01829287])

In [10]:
R @ point.reshape(3, 1) # Umwandlung in Spaltenvektor

array([[0.9932866 ],
       [0.11422393],
       [0.01829287]])

In [13]:
points = np.array([[1, 0, 0],
                  [0, 1, 0],
                  [0, 0, 1],
                  [1, 1, 1]])
points.shape 

(4, 3)

In [14]:
points @ R.T  

array([[ 0.9932866 ,  0.11422393,  0.01829287],
       [-0.11430465,  0.99343984,  0.00342628],
       [-0.01778151, -0.00549424,  0.9998268 ],
       [ 0.86120044,  1.10216953,  1.02154595]])

In [15]:
R @ points.T

array([[ 0.9932866 , -0.11430465, -0.01778151,  0.86120044],
       [ 0.11422393,  0.99343984, -0.00549424,  1.10216953],
       [ 0.01829287,  0.00342628,  0.9998268 ,  1.02154595]])